leapt_core_sitemap_default:
    path:     /sitemap.xml
    defaults: { _controller: LeaptCoreBundle:Sitemap:default, _format: xml }
    requirements:
        _format: xml

leapt_core_sitemap_sitemap:
    path:     /sitemap_{sitemap}.xml
    defaults: { _controller: LeaptCoreBundle:Sitemap:sitemap, _format: xml }
    requirements:
        _format: xml