services:
    debug.twig.extension:
        class: Twig_Extensions_Extension_Debug
        tags: [{ name: 'twig.extension' }]
    snowcap_core.image_type:
        class: Snowcap\CoreBundle\Form\Type\ImageType
        tags:
            - { name: form.type, alias: image }