parameters:
    leapt_core.google_analytics.tracking_id:
    leapt_core.google_analytics.debug:
    leapt_core.google_analytics.domain_name:
    leapt_core.google_analytics.allow_linker:
    leapt_core.paginator.template: ~

services:
    # Load twig text
    twig.extension.text:
        class: Twig_Extensions_Extension_Text
        tags: [ { name: 'twig.extension' } ]

    # Form types
    leapt_core.file_type:
        class: Leapt\CoreBundle\Form\Type\FileType
        tags:
            - { name: form.type }
        calls:
            - [ setUploadDir, [ %kernel.root_dir%/../web ] ]

    # Form type extensions
    leapt_core.collection_type_extension:
        class: Leapt\CoreBundle\Form\Extension\CollectionTypeExtension
        tags:
            - { name: form.type_extension, extended_type: Symfony\Component\Form\Extension\Core\Type\CollectionType }

    # Field entity event subscriber
    leapt_core.file_subscriber:
        class: Leapt\CoreBundle\Listener\FileSubscriber
        arguments: [ %kernel.root_dir%/../web ]
        tags:
            - { name: doctrine.event_subscriber}

    # Navigation
    leapt_core.navigation:
        class: Leapt\CoreBundle\Navigation\NavigationRegistry
        arguments: [ "@request_stack" ]

    leapt_core.twig_navigation:
        class: Leapt\CoreBundle\Twig\Extension\NavigationExtension
        arguments: [ "@leapt_core.navigation" ]
        tags:
            - { name: twig.extension }

    # Twig extensions
    leapt_core.twig_date:
        class: Leapt\CoreBundle\Twig\Extension\DateExtension
        arguments: [ "@translator" ]
        tags:
            - { name: twig.extension }

    leapt_core.twig_text:
        class: Leapt\CoreBundle\Twig\Extension\TextExtension
        tags:
            - { name: twig.extension }

    leapt_core.twig_google:
        class: Leapt\CoreBundle\Twig\Extension\GoogleExtension
        arguments: [ %leapt_core.google_analytics.tracking_id%, %leapt_core.google_analytics.debug% ]
        calls:
            - [ setDomainName, [ %leapt_core.google_analytics.domain_name% ]]
            - [ setAllowLinker, [ %leapt_core.google_analytics.allow_linker% ]]
            - [ setTagsManagerId, [ %leapt_core.google_tags_manager.id% ]]
        tags:
            - { name: twig.extension }

    leapt_core.twig_facebook:
        class: Leapt\CoreBundle\Twig\Extension\FacebookExtension
        arguments: [ %leapt_core.facebook.app_id% ]
        tags:
            - { name: twig.extension }

    leapt_core.twig_site:
        class: Leapt\CoreBundle\Twig\Extension\SiteExtension
        tags:
            - { name: twig.extension }

    leapt_core.twig_paginator:
        class: Leapt\CoreBundle\Twig\Extension\PaginatorExtension
        arguments: [ %leapt_core.paginator.template% ]
        calls:
            - [ setContainer, [ "@service_container" ]]
        tags:
            - { name: twig.extension }

    # RSS feeds
    leapt_core.feed_manager:
        class: Leapt\CoreBundle\Feed\FeedManager

    leapt_core.request_listener:
        class: Leapt\CoreBundle\Listener\RequestListener
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }

    # Google sitemap
    leapt_core.sitemap_manager:
        class: Leapt\CoreBundle\Sitemap\SitemapManager
        arguments: [ "@validator" ]
